#!/bin/bash

# setup
# gpg --homedir $home(below) --import /path/to/plaintext/publickey

# TODO: check for zero length files, both for encrypting files
# as well as encrypted files (gpg can currently error out
# and nothing is done about it).

# Reciepient
enc_for=SystemEncrypt

# settings dir
lib_dir=/usr/local/share/encrypt-system-files

#config and gpg home (should not need to change)
config=$lib_dir/config
home=$lib_dir/home

usage() {
  echo "Usage: $0 [-v] [-t recipient] [-g /path/to/gpg] [-m /gpghome] [-c /config]"
  exit 1
}

# get args
VERBOSE=0
while getopts "t:g:m:vh?" opt ; do
    case $opt in
      t) enc_for="$OPTARG" ;;
      v) VERBOSE=1 ;;
      g) gpg="$OPTARG" ;;
      m) home="$OPTARG" ;;
      c) config="$OPTARG" ;;
      h|\?) usage ;;
      *) echo "Unknown arg $opt" ; usage ;;
    esac
done

error() {
  echo $@
  exit 1
}
RET=0

vecho() {
  if [ $VERBOSE -ne 0 ] ; then
    echo $1
  fi
}

# checks
if ! [ -f "$config" ] ; then
  error "Config not found at $config"

elif ! [ -d "$home" ] ; then
  error "Gpg home not found at $home"

fi

# find gpg executable (only if user did not specify it - we check below)
if [ -z "$gpg" ] ;then
  for EACH in $(echo $PATH | sed 's/:/ /g') ; do
    for GPGNAME in gpg2 gpg ; do
      if [ -x "$EACH/$GPGNAME" ] ; then
        gpg="$EACH/$GPGNAME"
        break 2
      fi
    done
  done
fi
if ! [ -x "$gpg" ] ; then
  error "Failed to find gpg  $gpg"
fi

gpg_encrypt() {
  orig="$1"
  save="$2"
  # if we already have a .gpg version, check if original file has changed
  if [ -f "$save" ] ; then
    MTIME_OLD=$(ls -lt --full-time "$orig" | awk '{print $6,$7,$8}')
    MTIME_NEW=$(ls -lt --full-time "$save" | awk '{print $6,$7,$8}')
    
    if [ "$MTIME_OLD" == "$MTIME_NEW" ] ; then
      # files are the same
      vecho "...skipping already encrypted file $orig"
      return
    fi
  fi
  
  rm -f "$save"
  $gpg -q --batch --armor --homedir $home -r $enc_for --trust-model always --output "$save" --encrypt "$orig"
  if [ $? -eq 0 ] ; then
    vecho "__Encrypted__ $orig"
  else
    echo "ERROR: Failed to encrypt $orig"
    rm -f "$save"
    return 1
  fi
  fi
  
  # change perms based on original file's perms
  # YES, I know it doesn't technically matter, but why take the chance?
  chmod --reference="$orig" "$save"
  chown --reference="$orig" "$save"
  
  # set times to be the same for future encrypts
  MTIME_OLD=$(ls -lt --full-time "$orig" | awk '{print $6,$7,$8}')
  touch --date="$MTIME_OLD" "$save"

}

### Main ###

vecho "Using:"
vecho "Recipient ... $enc_for"
vecho "GPG exec  ... $gpg"
vecho "GPG Home  ... $home"
vecho "Config    ... $config"
vecho

# read config, and process each file/dir
cat $config | while read LINE ; do
  if [ -n "$(echo $LINE | grep ^#)" ] ; then
    # comment
    continue
  
  elif [ -z "$(echo $LINE | sed 's/ //g')" ] ; then
    # blank or empty line
    continue
  
  elif ! [ -e "$LINE" ] ; then
    # file or dir does not exist
    vecho "Skipping non-existant file/dir $LINE"
    continue
  
  fi
  
  if [ -f "$LINE" ] ; then
    gpg_encrypt "$LINE" "$LINE.gpg"
    [ $? -eq 0 ] || RET=1
    
  elif [ -d "$LINE" ] ; then
    # we do empty dirs. Skipping them would tell users they are empty.
    # this would be sensitive if the dirs were not world readable.
    vecho "Checking dir for files: $LINE"
    SAVEDIR="${LINE}_enc"
    mkdir -p "$SAVEDIR"
    chmod --reference="$LINE" "$SAVEDIR"
    chown --reference="$LINE" "$SAVEDIR"
    find "$LINE" -maxdepth 1 -type f | while read FILE ; do
      if [ -f "$FILE" ] ; then
        FILENAME="$(basename $FILE)"
	gpg_encrypt "$FILE" "$SAVEDIR/$FILENAME.gpg"
	[ $? -eq 0 ] || RET=1
      fi
    done
    # reset mod time
    MTIME_OLD=$(ls -ltd --full-time "$LINE" | awk '{print $6,$7,$8}')
    MTIME_NEW=$(ls -ltd --full-time "$SAVEDIR" | awk '{print $6,$7,$8}')
    if [ "$MTIME_NEW" != "$MTIME_OLD" ] ; then
      # just to make sure perms are still in sync
      chmod --reference="$LINE" "$SAVEDIR"
      chown --reference="$LINE" "$SAVEDIR"
      # do the actual sync of time
      touch --date="$MTIME_OLD" "$SAVEDIR"
    fi
  
  fi
  # hack to get while loop to give an correct RET value
  # just run a non-existant command at the last line
  # and if this is the last command in the loop,
  # it will exit with value 127, so we can check for it
  if [ $RET -ne 0 ] ; then
    nocommandfound234123409123840 >/dev/null 2>&1
  fi
done

if [ $? -ne 0 ] ; then
  RET=1
fi

vecho "Exiting with value $RET"
exit $RET
